gen_code_grpc:
	protoc \
		--go_out=grpc --go_opt=paths=source_relative \
  	--go-grpc_out=grpc --go-grpc_opt=paths=source_relative \
  	proto/*.proto
export_bin_go:
	export PATH="$PATH:$(go env GOPATH)/bin"